### ISSUE TITLE
Unexpected Crash

### ISSUE THREAD

**Issue by SkyWolfXP** [Emirlol/chatcalc#9]
Stacktrace:
```
java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonElement.getAsString()" because the return value of "com.google.gson.JsonObject.get(String)" is null
	at ca.rttv.chatcalc.Config.displayAbove(Config.kt:107)
	at net.minecraft.class_342.displayAbove(class_342.java:687)
	at net.minecraft.class_342.handler$zph000$chatcalc$renderWidget(class_342.java:676)
	at net.minecraft.class_342.method_48579(class_342.java:417)
	at net.minecraft.class_339.method_25394(class_339.java:66)
	at net.minecraft.class_408.method_25394(class_408.java:198)
	at net.minecraft.class_437.method_47413(class_437.java:117)
	at net.minecraft.class_757.mixinextras$bridge$method_47413$195(class_757.java)
	at net.minecraft.class_757.wrapOperation$cbp000$fabric-screen-api-v1$onRenderScreen(class_757.java:3586)
	at net.minecraft.class_757.method_3192(class_757.java:913)
	at net.minecraft.class_310.method_1523(class_310.java:1285)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
	```
	
`NullPointerException` is kinda wild ngl...

**Comment by Emirlol** [comment]
What's your config file like? Could you paste the contents of `chatcalc.json` from the config directory?

**Comment by SkyWolfXP** [comment]
> What's your config file like? Could you paste the contents of `chatcalc.json` from the config directory?

[chatcalc.json](https://github.com/user-attachments/files/16964456/chatcalc.json)

This was my old config from the old mod, Sorry I didn't think this would cause issues, I will delete it and let your fork generate a new config.

**Comment by Emirlol** [comment]
> This was my old config from the original mod, Sorry I didn't think this would cause issues, I will delete it and let your fork generate a new config.

Which version of the original mod are you talking about? The `display_above` config entry is also found in rttv's repo, so your config should've included that if you were using the latest version

**Comment by SkyWolfXP** [comment]
Hello @Emirlol 
Unfortunately deleting the config didn't fix it... Same error
